### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by 37OMKAR** [jbilcke-hf/FacePoke#26]
(facepoke) F:\facepocker>pip3 install --upgrade -r requirements.txt
Error processing line 1 of C:\Users\Omkar\AppData\Roaming\Python\Python310\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Users\Omkar\.conda\envs\facepoke\lib\site.py", line 195, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

[notice] A new release of pip is available: 24.1.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by jbilcke-hf** [comment]
Hi, it looks like you are not running the pip3 install command in the right folder,
as it says it couldn't find "requirements.txt"

normally you should run this command at the root of the FacePoke project, since this is where the "requirements.txt" is located

to make sure you are at the right place, you can try to list the files in the current dir first before launching the command

also I think you might have an issue with distutils, so you might need to first type this before attempting to install the requirements:

```bash
pip3 install -U pip setuptools
```
